name: shikon_voteapp
description: "A flutter project that provides voting service on the Shikon Fes."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  uuid: ^3.0.7
  shared_preferences: ^2.1.1
  mobile_scanner: any
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  provider: ^6.0.5
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  fl_chart: ^0.70.2
  collection: ^1.19.1
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  flutter_charts: ^0.5.2
  firebase_database: any
  connectivity_plus: ^6.1.3
  firebase_data_connect: ^0.1.0
  excel: ^2.1.0
  csv: ^5.0.2
  share_plus: ^7.1.0
  google_sign_in: any
  flutter_facebook_auth: any
  twitter_login: any
  camera: ^0.10.5+4
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2
  file_picker: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/help/
    - assets/Stage/
    - assets/First/
    - assets/Second/
    - assets/Third/